/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BannersRouteImport } from './routes/banners'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as EnquiriesRouteImport } from './routes/enquiries'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as ProductsRouteImport } from './routes/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesRoute = EnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/categories': typeof CategoriesRoute
  '/certifications': typeof CertificationsRoute
  '/company': typeof CompanyRoute
  '/enquiries': typeof EnquiriesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/manufacturing': typeof ManufacturingRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/categories': typeof CategoriesRoute
  '/certifications': typeof CertificationsRoute
  '/company': typeof CompanyRoute
  '/enquiries': typeof EnquiriesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/manufacturing': typeof ManufacturingRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/categories': typeof CategoriesRoute
  '/certifications': typeof CertificationsRoute
  '/company': typeof CompanyRoute
  '/enquiries': typeof EnquiriesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/manufacturing': typeof ManufacturingRoute
  '/products': typeof ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banners'
    | '/categories'
    | '/certifications'
    | '/company'
    | '/enquiries'
    | '/jobs'
    | '/login'
    | '/manufacturing'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banners'
    | '/categories'
    | '/certifications'
    | '/company'
    | '/enquiries'
    | '/jobs'
    | '/login'
    | '/manufacturing'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/banners'
    | '/categories'
    | '/certifications'
    | '/company'
    | '/enquiries'
    | '/jobs'
    | '/login'
    | '/manufacturing'
    | '/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BannersRoute: typeof BannersRoute
  CategoriesRoute: typeof CategoriesRoute
  CertificationsRoute: typeof CertificationsRoute
  CompanyRoute: typeof CompanyRoute
  EnquiriesRoute: typeof EnquiriesRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  ManufacturingRoute: typeof ManufacturingRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners': {
      id: '/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries': {
      id: '/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof EnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BannersRoute: BannersRoute,
  CategoriesRoute: CategoriesRoute,
  CertificationsRoute: CertificationsRoute,
  CompanyRoute: CompanyRoute,
  EnquiriesRoute: EnquiriesRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  ManufacturingRoute: ManufacturingRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
